# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: GHC 6023
email: ziqiw [at] alumni.cmu.edu
description: > # this means to ignore newlines until "baseurl:"
  Ziqi Wang
  <br />
  Carnegie Mellon Alumni
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wangziqi2013.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  wangziqi2013
github_username2:  wangziqi2016

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 5